<template>
  <svg
    class="w-8 h-8"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    style="
      margin: auto;
      background: rgba(0, 0, 0, 0) none repeat scroll 0% 0%;
      display: block;
      shape-rendering: auto;
    "
    viewBox="0 0 100 100"
    preserveAspectRatio="xMidYMid"
  >
    <rect x="18" y="30.5" width="14" height="39" fill="#ffffff">
      <animate
        attributeName="y"
        repeatCount="indefinite"
        dur="0.8403361344537814s"
        calcMode="spline"
        keyTimes="0;0.5;1"
        values="11;30.5;30.5"
        keySplines="0 0.5 0.5 1;0 0.5 0.5 1"
        begin="-0.1680672268907563s"
      ></animate>
      <animate
        attributeName="height"
        repeatCount="indefinite"
        dur="0.8403361344537814s"
        calcMode="spline"
        keyTimes="0;0.5;1"
        values="78;39;39"
        keySplines="0 0.5 0.5 1;0 0.5 0.5 1"
        begin="-0.1680672268907563s"
      ></animate>
    </rect>
    <rect x="43" y="30.5" width="14" height="39" fill="#ffffff">
      <animate
        attributeName="y"
        repeatCount="indefinite"
        dur="0.8403361344537814s"
        calcMode="spline"
        keyTimes="0;0.5;1"
        values="15.875;30.5;30.5"
        keySplines="0 0.5 0.5 1;0 0.5 0.5 1"
        begin="-0.08403361344537814s"
      ></animate>
      <animate
        attributeName="height"
        repeatCount="indefinite"
        dur="0.8403361344537814s"
        calcMode="spline"
        keyTimes="0;0.5;1"
        values="68.25;39;39"
        keySplines="0 0.5 0.5 1;0 0.5 0.5 1"
        begin="-0.08403361344537814s"
      ></animate>
    </rect>
    <rect x="68" y="30.5" width="14" height="39" fill="#ffffff">
      <animate
        attributeName="y"
        repeatCount="indefinite"
        dur="0.8403361344537814s"
        calcMode="spline"
        keyTimes="0;0.5;1"
        values="15.875;30.5;30.5"
        keySplines="0 0.5 0.5 1;0 0.5 0.5 1"
      ></animate>
      <animate
        attributeName="height"
        repeatCount="indefinite"
        dur="0.8403361344537814s"
        calcMode="spline"
        keyTimes="0;0.5;1"
        values="68.25;39;39"
        keySplines="0 0.5 0.5 1;0 0.5 0.5 1"
      ></animate>
    </rect>
    <!-- [ldio] generated by https://loading.io/ -->
  </svg>
</template>